Feature/140 add more sophisticated mechanism to link experiments
ebi-gene-expression-group/atlas-web-core pull request #113
Opened 2022-09-16 10:04 UTC by lingyun1010

Manual checks

- [ ] This branch is passing the CI tests as part of a pull request in the atlas-web-bulk or atlas-web-scxa repos and I have indicated that PR here.

2022-09-16 15:23 UTC, haideriqbal commented on src/main/java/uk/ac/ebi/atlas/trader/factory/BaselineExperimentFactory.java
> +                            altViewAccession.substring(2,6) == experimentAccession.substring(2,6) ?
Using `==` might land us in trouble in the future as this doesn't compare two strings value rather it just checks if two strings are referring to same object or not. A better way to compare would be using `equals` or `equalsIgnoreCase`.

Please review this link for further details: https://www.baeldung.com/java-compare-strings

2022-09-16 15:23 UTC, haideriqbal requested changes
Please review a small comment on string equality.

2022-09-21 15:08 UTC, haideriqbal requested changes
Please review the comment regarding making suggester service as an abstract class.

2022-09-21 15:08 UTC, haideriqbal commented on src/main/java/uk/ac/ebi/atlas/search/suggester/SuggesterService.java
> +public abstract class SuggesterService implements AnalyticsSuggesterService {
Why do we need to make this class as `abstract`?

2022-09-22 08:16 UTC, lingyun1010 commented on src/main/java/uk/ac/ebi/atlas/search/suggester/SuggesterService.java
> +public abstract class SuggesterService implements AnalyticsSuggesterService {
Due to a modification in atlas-web-core for atlas-web-single-cell, it will generate bean wiring issues otherwise.

2022-10-03 12:40 UTC, haideriqbal commented on src/main/java/uk/ac/ebi/atlas/search/suggester/SuggesterService.java
> +public abstract class SuggesterService implements AnalyticsSuggesterService {
I will be very careful in making this change. Suggester service is being used by other classes as well and making it `abstract` is breaking the code in other places. You cannot create an object of an abstract class and `suggesterService` is not designed to be an abstract class. (https://www.w3schools.com/java/java_abstract.asp)  I would suggest looking for another solution to bean issue you are facing rather than making this class abstract.

2022-10-04 13:37 UTC, haideriqbal commented
Hi @lingyun1010 couple of more points to rectify in the PR:

1. Please add a short description to the PR about what it is doing so that other developers are also aware of what problem is being solved. Also, please add a link to the bulk PR as well.
2. Please add test cases for the changes you have made.

2022-10-13 14:13 UTC, haideriqbal commented on src/test/java/uk/ac/ebi/atlas/trader/factory/BaselineExperimentFactoryTest.java
> +                                __ -> "E-PROT-1",
I suggest creating a separate test case for `Related` experiment accessions because changing the current test case to testing just one experiment in my opinion reduces the versatility of the original test case which is testing any random experiment.

2022-10-25 10:31 UTC, haideriqbal approved these changes
LGTM!

2022-10-26 09:12 UTC, merged