Chore – Remove experiment design
ebi-gene-expression-group/atlas-web-core pull request #121
Opened 2023-02-03 16:22 UTC by alfonsomunozpomer

Manual checks

- [ ] This branch is passing the CI tests as part of a pull request in the atlas-web-bulk or atlas-web-scxa repos and I have indicated that PR here.

2023-02-27 17:06 UTC, ke4 requested changes
I added some comments. Could you review them, please?
Thanks

2023-02-27 17:06 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/experimentimport/analyticsindex/conditions/ConditionsCollector.java
> +                                .parse(experiment.getAccession())
You could extract this line to a local variable:
`experimentDesignParser.parse(experiment.getAccession())`
as it is used twice. The code would look a bit cleaner.
Or event to a private method as it is used in other 2 methods, too.

2023-02-27 17:06 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTable.java
> +//        JsonArray headers = threeElementArray(
This looks like just returning a new `JsonObject` and have lots of commented code. Is this intentional? At least we should remove the commented lines.

2023-02-27 17:06 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTable.java
> +//    private JsonObject headerGroup(String name, Collection<String> members) {
Are these methods intentionally commented out?

2023-02-27 17:06 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/experimentimport/analyticsindex/conditions/ConditionsCollectorTest.java
> +                .thenReturn(experimentDesignMock);
```suggestion
        when(experimentDesignParserMock.parse(anyString()))
                .thenReturn(experimentDesignMock);
```

2023-02-27 17:06 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableTest.java
> +@Disabled
Is that `@Disabled` annotation accidentally left here?

2023-02-27 19:40 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTable.java
> +//    private JsonObject headerGroup(String name, Collection<String> members) {
Yes, everything related to `ExperimentDesignTable` is commented out intentionally because the JSON format will still be valid after everything is moved to the DB. Left as reference here. Do you think it’s better to remove it and retrieve it from the Git history?

2023-02-27 19:45 UTC, alfonsomunozpomer commented on src/test/java/uk/ac/ebi/atlas/experimentimport/analyticsindex/conditions/ConditionsCollectorTest.java
> +                .thenReturn(experimentDesignMock);
I think it’s better practice to narrow stubbed methods if we know the arguments that are going to be used when called.

2023-02-27 19:45 UTC, alfonsomunozpomer commented on src/test/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableTest.java
> +@Disabled
Yes, same rationale as in `ExperimentDesignTable` applies here.

2023-02-28 09:23 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTable.java
> +//    private JsonObject headerGroup(String name, Collection<String> members) {
That's why we use git. It has history. ;-)
I don't like commented code merged into the main branch. It looks very messy to me and far from clean code.
I like as less comments in the code as possibly. Better to use descriptive method and variable names instead of comments.

2023-02-28 09:25 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/experimentimport/analyticsindex/conditions/ConditionsCollectorTest.java
> +                .thenReturn(experimentDesignMock);
OK. You persuaded me and I agree with this. Let's leave it like you wrote it. Thanks

2023-02-28 09:27 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableTest.java
> +@Disabled
The problem is that we are going to forget this and we are going to leave this here for as long as the repo live. That means it has got almost zero value to have this disabled test here. Am I wrong?

2023-02-28 10:11 UTC, alfonsomunozpomer commented on src/test/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableTest.java
> +@Disabled
I don’t think so, the `ExperimentDesignTable` and its tests will live again. It will be returned by a controller instead of the page content serializer. My fear is that whoever takes this duty will forget about it and reimplement it from sratch. We can leave a `TODO` comment to remind ourselves...

2023-02-28 10:15 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableTest.java
> +@Disabled
If that is the case, then this needs to be added to the relevant ticket to re-enable this test again with that ticket. If that ticket is not exists, then we should create that ticket now and add this to the ticket.

2023-02-28 10:16 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableTest.java
> +@Disabled
`TODO` comments in the code is frequently ignored by the devs, unfortunately. That is my experience.

2023-02-28 10:32 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/experimentimport/analyticsindex/conditions/ConditionsCollector.java
> +                                .parse(experiment.getAccession())
I think that replacing this:
```java
Stream.of(
        ontologyIds,
        efoLookupService.getLabels(ontologyIds),
        experimentDesignParser
                .parse(experiment.getAccession())
                .getFactorValues(assayAccession)
                .values(),
        experimentDesignParser
                .parse(experiment.getAccession())
                .getSampleCharacteristicsValues(assayAccession)
                .values())
.flatMap(Collection::stream)
.collect(toSet());
```

With this:
```java
Stream.of(
        ontologyIds,
        efoLookupService.getLabels(ontologyIds),
        parseExperimentDesign(experiment.getAccession())
                .getFactorValues(assayAccession)
                .values(),
        parseExperimentDesign(experiment.getAccession())
                .getSampleCharacteristicsValues(assayAccession)
                .values())
.flatMap(Collection::stream)
.collect(toSet());
```

doesn’t really add much clarity (plus a level of indirection with the local method).

But it’s very true that we’re unnecessarily repeating work in the component. I’ve added a draft issue to our project.

2023-02-28 14:26 UTC, ke4 approved these changes
LGTM

2023-02-28 15:02 UTC, upendrakumbham commented on src/test/java/uk/ac/ebi/atlas/experimentpage/context/BaselineRequestContextTest.java
> +//    public void multiFactorExperimentWhereDisplayedColumnsShareAFactorShowsOnlyTheDifferentPart() {
are we going to uncomment the code
 this later?

2023-03-01 11:04 UTC, upendrakumbham approved these changes
All good! You clarified about commented code :).

2023-03-01 11:16 UTC, alfonsomunozpomer commented on src/test/java/uk/ac/ebi/atlas/experimentpage/context/BaselineRequestContextTest.java
> +//    public void multiFactorExperimentWhereDisplayedColumnsShareAFactorShowsOnlyTheDifferentPart() {
This is from a commit in the history, right? It’s not part of the final changes.

2023-03-01 11:16 UTC, merged