Experiment Design backend functionality
ebi-gene-expression-group/atlas-web-core pull request #123
Opened 2023-02-28 09:44 UTC by haideriqbal

This PR implements relevant classes to create experiment design table from data in the database rather than from experiment design file. The accompanying PR in [atlas-web-single-cell](https://github.com/ebi-gene-expression-group/atlas-web-single-cell/pull/324)

- [ ] This branch is passing the CI tests as part of a pull request in the atlas-web-bulk or atlas-web-scxa repos and I have indicated that PR here.

2023-06-13 16:37 UTC, ke4 requested changes
I requested some change in the code mostly to clean the code.
If something is not clear I am always available to discuss it.
Many thanks for your work

2023-06-13 16:37 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTable.java
>          JsonArray headers = threeElementArray(
This method name : `threeElementArray` is not telling me anything of its function. Shall we rename it to `headers` as it is more stating its function?

2023-06-13 16:37 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTable.java
> +    private List<String> getAssayHeaders(ExperimentType type) {
Please, consider to remove this method and add this functionality to the `ExperimentType` enum. That would also eliminate throwing an `IllegalArgumentException`, because we simply don't need it. Thanks

2023-06-13 16:37 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableService.java
> +    public JsonObject getExperimentDesignData(String experiment_accession, int pageNo, int pageSize) {
```suggestion
    public JsonObject getExperimentDesignData(String experimentAccession, int pageNo, int pageSize) {
```

2023-06-13 16:37 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableService.java
> +        return experimentDesignTable.asJson(experiment_accession, pageNo, pageSize);
```suggestion
        createExperimentDesignTable(experimentAccession, pageNo, pageSize)
            .asJson(experimentAccession, pageNo, pageSize);
```

2023-06-13 16:37 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableService.java
> +    }
```suggestion
    private ExperimentDesignTable createExperimentDesignTable(String experimentAccession, int pageNo, int pageSize) {
        return new ExperimentDesignTable(experimentTrader.getExperiment(experimentAccession, ""), this.experimentDesignDao);
    }
```

2023-06-13 16:37 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/trader/ExperimentDesignDao.java
> +                                }
```suggestion
                                var sampleType = result.getOrDefault(key, new ArrayList<>());
                                sampleType.add(value);
                                result.put(key, sampleType);
```

2023-06-13 16:37 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/trader/ExperimentDesignDao.java
> +                    var result = new ArrayList<LinkedHashMap<String, List<String>>>();
Let's clean this code a bit. 😉
I suggest to create a new Value Object with these 2 properties: `characteristics` and `factorValues`. You can use Lombok's `@Value` annotation for that. Thanks

2023-06-13 16:37 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/trader/ExperimentDesignDao.java
> +                          }
```suggestion
                          var sampleAnnotations = assayToCharacteristics.getOrDefault(sample, new ArrayList<>());
                          sampleAnnotations.add(annotValue);
                          assayToCharacteristics.put(sample, sampleAnnotations);
```

2023-06-13 16:37 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/trader/ExperimentDesignDao.java
> +                            }
```suggestion
                          var sampleAnnotations = assayToFactorValues.getOrDefault(sample, new ArrayList<>());
                          sampleAnnotations.add(annotValue);
                          assayToFactorValues.put(sample, sampleAnnotations);
```

2023-06-13 16:37 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/trader/ExperimentDesignDao.java
> +                    var result = new ArrayList<LinkedHashMap<String, List<String>>>();
I suggest to use the same Value Object that I suggested above just add another property next to the other 2: `arrayDesigns`. Thanks

2023-06-13 16:37 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/trader/ExperimentDesignDao.java
> +                            }
```suggestion
                          var sampleAnnotations = assayToCharacteristics.getOrDefault(sample, new ArrayList<>());
                          sampleAnnotations.add(annotValue);
                          assayToCharacteristics.put(sample, sampleAnnotations);
```

2023-06-13 16:37 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/trader/ExperimentDesignDao.java
> +                            }
```suggestion
                          var sampleAnnotations = assayToFactorValues.getOrDefault(sample, new ArrayList<>());
                          sampleAnnotations.add(annotValue);
                          assayToFactorValues.put(sample, sampleAnnotations);
```

2023-06-13 16:37 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/trader/ExperimentDesignDao.java
> +                        }
```suggestion
                        var sampleAnnotations = assayToArrayDesigns.getOrDefault(sample, new ArrayList<>());
                        sampleAnnotations.add(arrayDesign);
                        assayToArrayDesigns.put(sample, sampleAnnotations);
```

2023-06-13 16:37 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableServiceTest.java
> +        assertThat(result.get("totalNoOfRows").getAsInt()).isEqualTo(100);
I assume this magic number `100` is the same magic number as in line 40. Let's introduce a constant for that magic number: `expectedTotalNoOfRows`. Thanks

2023-06-13 16:37 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableServiceTest.java
> +        assertThat(result.get("headers").isJsonArray()).isTrue();
Could we think of a better way to check the content of the header and the same for the data in the next line?

2023-06-13 16:37 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableTest.java
> +        assertThat(result.get("totalNoOfRows").getAsInt()).isEqualTo(100);
Please, change the magic number to a variable as I wrote it above. Thanks

2023-06-13 16:37 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableTest.java
> +        assertThat(result.get("headers").isJsonArray()).isTrue();
We don't need this assertion as we have the same assertion in the next line.

2023-06-22 08:03 UTC, lingyun1010 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTable.java
>          JsonArray headers = threeElementArray(
This is just a basic function, it doesn't have to be `headers`, it depends on what we put in the parameters, so I think this function name is fair enough.

2023-07-14 09:15 UTC, ke4 requested changes
I added some comments for your changes. Could you please review and consider them? Thanks

2023-07-14 09:15 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTable.java
>          var experiment_type = experiment.getType();
In this method there are a couple of variables with snake case. 

- experiment_accession
- experiment_type

Unfortunately I missed them in my 1st review. Please change them to camel case. 
This tells me that this code segments could contains other parts as well that have variables with snake case. Could you also check this please and change them?
Thanks

2023-07-14 09:15 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTable.java
>          JsonArray headers = threeElementArray(
I strongly disagree.
From Oracle Java doc: `Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalised.`
I would also add that the name should describe what the method does.
Just think if you are a newcomer, you would ask why do we need to create an array with 3 elements? Why 3 why not 4 or 5? The name of the method should clearly tell the user what it does and why.

2023-07-14 09:15 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentType.java
> +    RNASEQ_MRNA_BASELINE("rnaseq_mrna_baseline", "RNA-Seq mRNA baseline", Lists.newArrayList("Run")),
I think you can simplify this and make the 3rd parameter only a `String` and use the `List.of()` method in the constructor instead of the `Lists.newArrayList()` in the enum constant definition.

2023-07-14 09:15 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/trader/ExperimentDesignDao.java
> +                                result.put(key, sampleType);
This line is unnecessary. `sampleType` is a reference to a value in the `result` `Map` variable.
could you remove it, please?

2023-07-14 09:15 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/trader/ExperimentDesignDao.java
> +    @Value
I am afraid this is not how to use properly the `@Value` annotation from Lombok. You don't have to write all of these boiler plate code.
I suggest to read this article: http://www.javabyexamples.com/lombok-data-and-value-for-fast-pojos
I hope after that you can reduce this code for only 5 lines including the class name and the closing `}`.
Also, please use interfaces and not implementations when you define a field. Thanks

2023-07-14 09:15 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/trader/ExperimentDesignDao.java
> +                            assayToCharacteristics.computeIfAbsent(sample, k -> new ArrayList<>()).add(annotValue);
This code is doing a totally different action that you are about to replace. Are you sure your change is correct? We could discuss this if you would like to? Thanks

2023-07-14 09:15 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/trader/ExperimentDesignDao.java
> +                            assayToCharacteristics.computeIfAbsent(sample, k -> new ArrayList<>()).add(annotValue);
Please see above my comment regarding to this.

2023-07-14 09:15 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/trader/ExperimentDesignDao.java
> +                        assayToArrayDesigns.put(sample, sampleAnnotations);
This line is not needed. See my similar comment above.

2023-07-14 09:15 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableServiceTest.java
> +        var totalNoOfRows = result.get("totalNoOfRows").getAsInt();
You can inline these variable into the `assertThat` statements. I think the code would be more readable.

2023-08-22 12:29 UTC, ke4 requested changes
I added 1 more comment about the `ExperimentDesignData` class and I noticed that you have not resolved a couple of older comments/suggestions.
Could you please take care of these comments?

Many thanks,
Karoly

2023-08-22 12:29 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/trader/ExperimentDesignData.java
> +    public Map<String, List<String>> getCharacteristics() {
We don't need these getters. They are coming with the @Value annotation. Could you please remove them? Thanks

2023-09-28 09:59 UTC, upendrakumbham requested changes
A minor code optimisation in the controller.

2023-10-20 10:54 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTable.java
>          var experiment_type = experiment.getType();
This class has ben removed

2023-10-20 10:54 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableTest.java
> +        assertThat(result.get("headers").isJsonArray()).isTrue();
This class has been removed

2023-10-20 10:55 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableTest.java
> +        assertThat(result.get("totalNoOfRows").getAsInt()).isEqualTo(100);
This class has been removed

2023-10-20 10:55 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableServiceTest.java
> +        assertThat(result.get("headers").isJsonArray()).isTrue();
This class has been removed

2023-10-20 10:55 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableServiceTest.java
> +        assertThat(result.get("totalNoOfRows").getAsInt()).isEqualTo(100);
This class has been removed.

2023-10-20 10:55 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableService.java
> +    }
This class has been removed.

2023-10-20 10:56 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableService.java
> +        return experimentDesignTable.asJson(experiment_accession, pageNo, pageSize);
This class has been removed.

2023-10-20 10:56 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTableService.java
> +    public JsonObject getExperimentDesignData(String experiment_accession, int pageNo, int pageSize) {
This class has been removed.

2023-10-20 10:56 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTable.java
> +    private List<String> getAssayHeaders(ExperimentType type) {
This class has been removed.

2023-10-20 10:57 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentDesignTable.java
>          JsonArray headers = threeElementArray(
This class has been removed.

2023-10-20 11:02 UTC, ke4 approved these changes
I tried to fix all the broken code and removed the unneeded code (whole classes or just methods/variables).
I executed the tests using `atlas-web-single-cell` repo and they all passed.
I would like to merge this version as soon as possible and go ahead with the other PR in `atlas-web-single-cell` repo using this version of `atlas-web-core`.
If we need any changes than we can do it with another PR.
Thanks

2023-10-20 13:42 UTC, upendrakumbham approved these changes
ALGTM!

2023-10-20 13:47 UTC, merged