Chore – Integration tests for atlas web core
ebi-gene-expression-group/atlas-web-core pull request #128
Opened 2023-05-26 09:53 UTC by alfonsomunozpomer

Manual checks

- [x] This branch is passing the CI tests as part of a pull request in the atlas-web-bulk or atlas-web-scxa repos and I have indicated that PR here. 

This PR includes a .env file to run integration tests, and some fixes to a few tests that were failing after some time of neglect. See also https://github.com/ebi-gene-expression-group/atlas-web-single-cell/pull/346 and https://github.com/ebi-gene-expression-group/atlas-web-bulk/pull/154 for context.

2023-05-30 12:45 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/utils/EuropePmcClient.java
> +        // You can remove this check and this comment if EuropePmc fix this bug
@alfonsomunozpomer Has this bug been reported to EuropePMC, yet?
Would be better to add a bug ID to this comment. That way a person encounter this class could check if that has been fixed yet, or not.

2023-05-30 13:17 UTC, ke4 requested changes
It looks good, but I added some comments related to magic word(s)/number(s).
I know it was most probably not added by you, but as you changed them you just won the option to fix this issue. Sorry about that. 😊

2023-05-30 13:17 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/bioentity/properties/BioEntityCardPropertiesIT.java
> +    @RepeatedTest(100)
Is this intentionally added or accidentally left here? Thanks

2023-05-30 13:17 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/solr/analytics/query/AnalyticsQueryClientIT.java
> +                    .queryIdentifierSearch(SemanticQuery.create(SemanticQueryTerm.create("GO:1234567", "go")))
Is it possible to replace all of the magic words with randomly generated values?
I meant these ones: `GO:1234567`, `go`, `E-MTAB-513`.
Thanks

2023-05-30 13:17 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/solr/analytics/query/AnalyticsQueryClientIT.java
> +                    .queryIdentifierSearch(SemanticQuery.create(SemanticQueryTerm.create("ENSG00000006432")))
magic words ^^^

2023-05-30 13:17 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/solr/analytics/query/AnalyticsQueryClientIT.java
> +                    .ofSpecies("oryza sativa")
magic words ^^^

2023-05-30 13:17 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/solr/analytics/query/AnalyticsQueryClientIT.java
> +                    .queryIdentifierSearch(SemanticQuery.create("zinc finger"))
magic words ^^^

2023-05-30 13:17 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/solr/analytics/query/AnalyticsQueryClientIT.java
> +                    .queryIdentifierSearch(SemanticQuery.create("zinc finger"))
magic words ^^^

2023-05-30 13:17 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/solr/analytics/query/AnalyticsQueryClientIT.java
> +                    .queryIdentifierSearch(SemanticQuery.create("zinc finger"))
magic words ^^^

2023-05-30 13:17 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/solr/analytics/query/AnalyticsQueryClientIT.java
> +                    .queryIdentifierOrConditionsSearch(SemanticQuery.create("tasty pancake"))
magic words ^^^

2023-05-30 13:17 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/utils/EuropePmcClientIT.java
> +        var result = subject.getPublicationByDoi("10.1126/sciimmunol.aan8664");
Sorry, but if it is possible to mock it, then we should. Removes the possibility to have a broken test if `EuropePMC` removes that publication.

2023-05-30 13:17 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/utils/EuropePmcClientIT.java
> +        var result = subject.getPublicationByPubmedId("29352091");
magic word ^^^

2023-05-30 13:17 UTC, ke4 commented on src/test/resources/fixtures/gxa/experiment.sql
> +-- INSERT INTO experiment (accession, type, access_key, last_update, pubmed_ids, dois, private, species, load_date) VALUES ('E-MTAB-5423', 'RNASEQ_MRNA_BASELINE', '0f54bd3e-633d-4431-be0e-f0f0c7e762b
We either need to remove this line or add it back without commented it out.

2023-05-30 13:21 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/utils/EuropePmcClient.java
> +        // You can remove this check and this comment if EuropePmc fix this bug
I reported via [EuropePMC’s helpdesk](https://europepmc.org/ContactUs) so, as far as I know, there’s no external ID we can check. The helpdesk ticket ID from the reply is EuropePMC #657887.

2023-05-31 09:26 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/utils/EuropePmcClient.java
> +        // You can remove this check and this comment if EuropePmc fix this bug
I created a message regarding this issue here: https://groups.google.com/a/ebi.ac.uk/g/epmc-webservices.
I guess we could resolve this conversation now and whenever we got a response to my message we could just create a simple PR with a commit with the addition of the ticket URL

2023-05-31 09:41 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/utils/EuropePmcClientIT.java
> +                .hasFieldOrPropertyWithValue("doi", "10.1126/sciimmunol.aan8664")
This bit is a little weird to me as we are trying to get a publication by a generated random DOI, then we check if the response contains not that random DOI, but a hardcoded one.

2023-05-31 09:51 UTC, ke4 reviewed
I added some comments. We can discuss it on today's standup.
Thanks for your work on this.

2023-05-31 09:51 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/utils/EuropePmcClientIT.java
> +                .hasFieldOrPropertyWithValue("pubmedId", "29352091")
The same as above ^^^

2023-05-31 09:51 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/utils/EuropePmcClientIT.java
> +        //         .andRespond(withSuccess(EMPTY_RESPONSE, MediaType.APPLICATION_JSON));
Is the `EMPTY_RESPONSE` constant value define somewhere? I can't see it. Maybe my bad.

2023-05-31 09:51 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/utils/EuropePmcClientIT.java
> +    @Test
Shall we disable/ignore this test as it is not adding any value for now?

2023-05-31 10:05 UTC, alfonsomunozpomer commented on src/test/java/uk/ac/ebi/atlas/utils/EuropePmcClientIT.java
> +        //         .andRespond(withSuccess(EMPTY_RESPONSE, MediaType.APPLICATION_JSON));
This is from an earlier version of the code. I’ll replace it with the `europepmc-no-results-response.json` resource.

2023-05-31 10:05 UTC, alfonsomunozpomer commented on src/test/java/uk/ac/ebi/atlas/utils/EuropePmcClientIT.java
> +    @Test
It still checks a code path that exists in the main classes, so I think we should keep it.

2023-05-31 12:10 UTC, alfonsomunozpomer commented on src/test/java/uk/ac/ebi/atlas/utils/EuropePmcClientIT.java
> +                .hasFieldOrPropertyWithValue("doi", "10.1126/sciimmunol.aan8664")
As agreed, I changed the test to disregard the random DOI/PubMed ID and just check that the retrieved fields from the example JSON response aren’t empty.

2023-05-31 12:11 UTC, alfonsomunozpomer commented on src/test/java/uk/ac/ebi/atlas/utils/EuropePmcClientIT.java
> +                .hasFieldOrPropertyWithValue("pubmedId", "29352091")
The same as above ^^^ :P

2023-05-31 13:11 UTC, ke4 approved these changes
Look perfect. 💯 👍 Thanks for all your hard work.

2023-05-31 13:35 UTC, merged