Chore/marker genes only search
ebi-gene-expression-group/atlas-web-core pull request #129
Opened 2023-05-26 16:12 UTC by alfonsomunozpomer

Manual checks

- [ ] This branch is passing the CI tests as part of a pull request in the atlas-web-bulk or atlas-web-scxa repos and I have indicated that PR here.

2023-05-31 15:17 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/resource/DataFileHubIT.java
> +// TODO Rethink this test since not all experiments have inferred cell type annotations
Shall we have a `fetchRandomExperimentAccessionForInferredCellTypes()` method and that would only return a random accession from a set of experiment accessions that HAS inferred cell type annotations?

2023-05-31 15:20 UTC, ke4 requested changes
Look great! Just a small comment to be able to enable a test.
Thanks for your work 👍

2023-05-31 15:20 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/resource/DataFileHubIT.java
> +// TODO Rethink this test since not all experiments have inferred cell type annotations
Shall we have a fetchRandomExperimentAccessionForInferredCellTypes() method and that would only return a random accession from a set of experiment accessions that HAS inferred cell type annotations?
That way we could enable this test...

2023-06-02 09:41 UTC, alfonsomunozpomer commented on src/test/java/uk/ac/ebi/atlas/resource/DataFileHubIT.java
> +// TODO Rethink this test since not all experiments have inferred cell type annotations
I moved this test to `DataFileHubIT` in `/app` and added the method as we discussed. However, read my comments in https://github.com/ebi-gene-expression-group/atlas-web-single-cell/pull/348 regarding `DataFileHub`.

2023-06-02 13:35 UTC, ke4 approved these changes
Looks fine by me 👍

2023-06-02 14:21 UTC, merged