Catch the error where experiment has no secondary accessions provided in idf file
ebi-gene-expression-group/atlas-web-core pull request #140
Opened 2024-04-17 15:45 UTC by lingyun1010

Manual checks

- [ ] This branch is passing the CI tests as part of a pull request in the atlas-web-bulk or atlas-web-scxa repos and I have indicated that PR here.

2024-04-17 16:12 UTC, ke4 requested changes
I added some request for consideration. We can discuss it tomorrow if it is not clear.
Thanks

2024-04-17 16:12 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/experimentpage/ExternallyAvailableContentService.java
> +        } catch(Exception e){
This looks like a too wide catch. Could we narrow it down and make it a bit more specific, please?
Thanks

P.S.: I am also wondering why are we throwing exception in the above code if there is no secondary exception. It is a bit strange to me. Probably we should return with an empty list or something relevant, but not an exception. And if we change that code to this, then we don't even need this `catch` block.

2024-04-17 16:12 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/experimentpage/ExternallyAvailableContentService.java
> +           LOGGER.info("Experiment: {} has no secondary accessions.", experiment.getAccession());
I think we could change this to `debug` level to not make our logger too chatty.

2024-04-18 16:12 UTC, ke4 commented
@lingyun1010 With a little bit of debugging I found the root cause of the problem.
In the `LinkToPride` class we have these `private static final` fields:

```
    private static final Function<BaselineExperiment, String> formatLabel =
            e -> MessageFormat.format("PRIDE Archive: project {0}", e.getSecondaryAccessions().stream().findAny().get());
    private static final Function<BaselineExperiment, String> formatLink =
            e -> MessageFormat.format("https://www.ebi.ac.uk/pride/archive/projects/{0}", e.getSecondaryAccessions().stream().findAny().get());
```

This code suspects that we always have `secondaryAccession` for an experiment. Even IntelliJ marks the `get()` call and tells us: `If a value is present, returns the value, otherwise throws NoSuchElementException.`

So, I suggest to correct these lines and then we don't have to deal with a wrongly thrown exception.

If it is not clear, then we can discuss it tomorrow.

Thanks

2024-04-18 16:23 UTC, ke4 commented
By the way in these lines the `findAny()` call is a bit weird to me. 

```
 private static final Function<BaselineExperiment, String> formatLabel =
            e -> MessageFormat.format("PRIDE Archive: project {0}", e.getSecondaryAccessions().stream().findAny().get());
    private static final Function<BaselineExperiment, String> formatLink =
            e -> MessageFormat.format("https://www.ebi.ac.uk/pride/archive/projects/{0}", e.getSecondaryAccessions().stream().findAny().get());
```

From the JavaDoc: 
`The behaviour of this operation is explicitly nondeterministic; it is free to select any element in the stream. This is to allow for maximal performance in parallel operations; the cost is that multiple invocations on the same source may not return the same result. (If a stable result is desired, use findFirst() instead.)`

2024-04-22 13:46 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPride.java
> +        try {
I am sorry, but this is not the way to fix this bug.
We need to refactor this code to not throw this `NoSuchElementException` exception.
In my previous comment that I added to this ticket I already suggested the lines that we need to refactor. Those are the lines where we call a `get()` on an `Optional` without checking if it has any values.

2024-04-22 16:53 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPride.java
> +        return  experiment.getSecondaryAccessions().isEmpty() ? Collections.emptyList() :
Unfortunately, this is still not fixing the issue in line 18 and 20. 
`findAny()` is a non-deterministic method. Could be return any value from a collection.
Also, it would be better to just pass a String value to those variables (`formatLabel`, `formatLink` and `createIcon`) and get that string value in this current `get` method.
Thanks

2024-04-23 09:43 UTC, lingyun1010 commented on src/main/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPride.java
> +        return  experiment.getSecondaryAccessions().isEmpty() ? Collections.emptyList() :
It did fix the issue actually and I tested locally which is working fine. We only call `formatLabel`, `formatLink` and `createIcon` when the `secondaryAccessions` is not empty so it wouldn't cause any issues to call `findAny()`. Please check it again or run locally to test. Thanks.

2024-04-23 11:38 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPride.java
> +        return  experiment.getSecondaryAccessions().isEmpty() ? Collections.emptyList() :
@lingyun1010 I understand that your changes is going to fix the bug, but we are also trying to clean the code where we can. I would like to leave a cleaner code that we had before.
Please, read my suggestions above. That should help you how to do it.
Thanks for your effort

2024-04-24 10:16 UTC, ke4 requested changes
Your code is doing that we discussed yesterday. Well done.
I just wanted to make it more clean and readable to the later coming developer, so I added some suggestions. You only have to click on the `Commit suggestions` button to make the commits.
We also need the modified test cases that we discussed today's status meeting.
Thanks for your work

2024-04-24 10:16 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPride.java
> +                        .collect(Collectors.toCollection(ArrayList::new));
Make this more readable for the later coming developer
```suggestion
        var secondaryAccessions = experiment.getSecondaryAccessions();

        if (!secondaryAccessions.isEmpty()) {
            return getExternallyAvailableContents(secondaryAccessions);
        } else {
            return emptyContent();
        }
```

2024-04-24 10:16 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPride.java
Please add these private methods to the and of the class. Thanks
```suggestion
@NotNull
    private static List<ExternallyAvailableContent> emptyContent() {
        return Collections.emptyList();
    }

    @NotNull
    private static List<ExternallyAvailableContent> getExternallyAvailableContents(ImmutableSet<String> secondaryAccessions) {
        return secondaryAccessions.stream()
                .map(secondaryAccession -> new ExternallyAvailableContent(
                                formatLink.apply(secondaryAccession),
                                createIcon.apply(secondaryAccession)
                        )
                )
                .collect(Collectors.toList());
    }
```

2024-04-26 10:52 UTC, ke4 requested changes
I added some tiny comments. Could you fix them, please?
Otherwise good to go.
Thanks

2024-04-26 10:52 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/experimentpage/ExternallyAvailableContentService.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(ExternallyAvailableContentService.class);
You added this `LOGGER`, but you are not using it.
Could you please remove it, if it is not needed.
If it was a temporary addition that's exactly what you can achieve with IntelliJ's non-suspending logging in the Debugger.
Thanks

2024-04-26 10:52 UTC, ke4 commented on src/main/java/uk/ac/ebi/atlas/experimentpage/ExternallyAvailableContentService.java
> +       return   suppliers.stream()
Probably you added these 2 spaces accidentally.

2024-04-26 10:52 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPrideIT.java
> +                        new URI("redirect:https://www.ebi.ac.uk/pride/archive/projects/" + accession1))
You can extract `"redirect:https://www.ebi.ac.uk/pride/archive/projects/"` to a class level constant and use it in the previous method, too.

2024-04-26 10:52 UTC, ke4 commented on src/test/java/uk/ac/ebi/atlas/experimentpage/link/LinkToPrideIT.java
> +                        ExternallyAvailableContent.Description.create("icon-pride", "PRIDE Archive: project " + accession1));
You can extract ""PRIDE Archive: project "" to a class level constant and use it in the previous method, too.

2024-04-26 12:44 UTC, ke4 approved these changes
LGTM!
Thanks for your work

2024-04-27 16:46 UTC, merged