Allow cell type marker gene file added to archive
ebi-gene-expression-group/atlas-web-core pull request #58
Opened 2020-12-15 12:07 UTC by lingyun1010

The {marker_gene_[numbers]} are already included in the archive, and this story is to add the files named like `maker_gene_inferred_cell_type_-_ontology_labels`, so I add a new matcher.

2020-12-15 23:10 UTC, alfonsomunozpomer requested changes
Please add some tests.

2020-12-21 17:18 UTC, upendrakumbham commented on src/test/java/uk/ac/ebi/atlas/resource/DataFileHubIT.java
> +            String experimentAccession = "E-MTAB-5061";
Can you make this test case a generic one? We can call `jdbcTestUtils.fetchRandomSingleCellExperimentAccessionWithMarkerGenes()` to get an experiment accession randomly.

2020-12-21 17:25 UTC, upendrakumbham requested changes
Please modify the test case to test cell type marker gene files randomly. If you have a dependency on the latest test data to make this test case generic, let me know I will approve this PR.

2020-12-23 12:20 UTC, haideriqbal commented on src/main/java/uk/ac/ebi/atlas/resource/DataFileHub.java
> +        }
Please refactor this function using `var` as variable types.

2020-12-23 12:21 UTC, haideriqbal commented on src/test/java/uk/ac/ebi/atlas/resource/DataFileHubIT.java
> +
Same goes for here as mentioned above 🆙

2020-12-23 12:29 UTC, haideriqbal approved these changes
Please see the comments and make the changes before merging the PR

2020-12-23 13:12 UTC, upendrakumbham approved these changes
LGTM. Please merge away.

2020-12-24 07:32 UTC, merged