Feature/173964655 add proteomics differential experiment type
ebi-gene-expression-group/atlas-web-core pull request #69
Opened 2021-09-24 09:55 UTC by lingyun1010

This PR comes with the bulk branch https://github.com/ebi-gene-expression-group/atlas-web-bulk/tree/feature%2F173964655-add-proteomics-differential

2021-10-20 09:58 UTC, upendrakumbham commented
I'm getting the above issue when trying to see the experiments page. But when I hit `http://localhost:8080/gxa/json/experiments/E-PROT-39` endpoint, I could see the JSON payload for the experiment: E-PROT-39.

2021-11-03 11:36 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/experimentpage/ExperimentDownloadSupplier.java
> +                preferences.setCutoff(0.5);
Have you verified with curators that this is the default values we want?

2021-11-03 12:31 UTC, alfonsomunozpomer requested changes
As mentined in my previous review, generalising the stream and writer factory requires also thought to rename their generic data types.

Also, going back to basic fundamentals of software engineering (and system design), it’s a bad habit to generalise a class or component by enumerating its implemented types.

For example, let’s say I have a `Koala` class:
```java
public class Koala {
  public void breathes(){};
  public void eatsEukalyptus(){};
}
``` 

And then I add a new class, `Sloth`:
```java
public class Sloth {
  public void breathes(){};
  public void eatsTenderShoots(){};
}
```

The right way to generalise these two types is:
```java
public class ArborealAnimal {
  public void breathes(){};
}
```

```java
public class Koala extends Animal {
  public void eatsEukalyptus(){};
}
```

```java
public class Sloth extends Animal {} {
  public void eatsTenderShoots(){};
}
```

If you apply the logic applied in this PR we would have something like:
```java
public class KoalaAndSloth {
  public void breathes(){};

  public void eats(){
    // Eukalyptus if it’s a koala
    // Tender shoots if it’s a sloth
  };
}
```

So, if you generalise a class the name should also be general, rather than enumerating the real world objects it maps to. You can see how the second approach becomes less manageable as more animals are added to the system.

2021-11-03 12:31 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/profiles/stream/RnaSeqAndProteomicsProfileStreamFactory.java
>          extends ProfileStreamFactory<Contrast,
Notice that `RnaSeqAndProteomicsProfileStreamFactory` is extending a `ProfileStreamFactory` of `RnaSeqRequestContext` and `RnaSeqProfile`, which kind of breaks the semantics of the class hierarchy.

2021-11-03 12:31 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/profiles/writer/RnaSeqAndProteomicsDifferentialProfilesWriterFactory.java
> +public class RnaSeqAndProteomicsDifferentialProfilesWriterFactory extends
Similar as above, `RnaSeqAndProteomicsDifferentialProfilesWriterFactory` extends a writer factory for `RnaSeqProfile` and `RnaSeqRequestContext`.

2021-11-18 11:14 UTC, alfonsomunozpomer approved these changes
So much better! Actually I think `BulkDifferential...` is a much better name than `RnaSeq...` because it better represents more accurately what these classes are about. Good choice.

The only thing remaining is to rename the test class `RnaSeqProfileStreamFactoryPickUpExpressionsByIndexTest` to `BulkDifferentialProfileStreamFactoryPickUpExpressionsByIndexTest` and all good.

2021-11-18 11:14 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/experimentpage/ExperimentDownloadSupplier.java
> +import uk.ac.ebi.atlas.profiles.stream.*;
Expand wildcard imports, please.

2021-11-18 12:11 UTC, merged