Feature/175873830 scxa analytics suggesters for search box rebase
ebi-gene-expression-group/atlas-web-core pull request #73
Opened 2021-10-07 13:19 UTC by upendrakumbham

This PR is about - Scxa analytics metadata suggestions implementation. This feature allows users to see suggestions for the organism, organism part, disease, and cell types in the gene search box.

Associated `SCXA` PR  - https://github.com/ebi-gene-expression-group/atlas-web-single-cell/pull/200

2021-10-15 13:19 UTC, alfonsomunozpomer requested changes
There are some suggestions to improve here.

Also, a general note: the English word “metadata” is correct. See https://en.wikipedia.org/wiki/Metadata. Please replace `metaData` or variants to just `metadata`.

2021-10-15 13:19 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/search/suggester/AnalyticsSuggesterDao.java
> +
Unneeded blank line.

2021-10-15 13:19 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/search/suggester/AnalyticsSuggesterService.java
> +
Unneeded blank line.

2021-10-15 13:19 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/search/suggester/AnalyticsSuggesterService.java
> +import org.springframework.stereotype.Service;
Stale import.

2021-10-15 13:19 UTC, alfonsomunozpomer commented on src/test/java/uk/ac/ebi/atlas/search/suggester/SolrSuggestionReactSelectAdapterTest.java
> +        ArrayList<AnalyticsPropertyName> idPropertyNames = new ArrayList<>(ANALYTICS_SUGGESTER_NAMES_FOR_METADATA_SEARCH);
I don’t think `idPropertyNames` is a good variable name. Also, now that you’re at it, you can `var`-ify the code in this class.

2021-10-15 13:19 UTC, alfonsomunozpomer commented on src/test/java/uk/ac/ebi/atlas/search/suggester/SolrSuggestionReactSelectAdapterTest.java
> +    void metaDataSuggestionsAreGroupedByCategory(List<AnalyticsPropertyName> idPropertyNames) {
Change `idPropertyNames` to something that makes more sense.

2021-10-15 13:19 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/search/suggester/SolrSuggestionReactSelectAdapter.java
> +    }
You’re duplicating a big chunk of code here. Please [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself) it out.

2021-10-15 14:44 UTC, upendrakumbham commented on src/main/java/uk/ac/ebi/atlas/search/suggester/SolrSuggestionReactSelectAdapter.java
> +    }
True, Thanks. I fix it.

2021-10-20 15:17 UTC, upendrakumbham commented on src/main/java/uk/ac/ebi/atlas/search/suggester/AnalyticsSuggesterDao.java
> +
Fixed

2021-10-21 09:05 UTC, upendrakumbham commented on src/main/java/uk/ac/ebi/atlas/search/suggester/SolrSuggestionReactSelectAdapter.java
> +    }
done

2021-10-21 09:42 UTC, upendrakumbham commented
> Also, a general note: the English word “metadata” is correct. See https://en.wikipedia.org/wiki/Metadata. Please replace `metaData` or variants to just `metadata`.

Got it.

2021-11-09 10:22 UTC, upendrakumbham commented on src/main/java/uk/ac/ebi/atlas/search/suggester/SolrSuggestionReactSelectAdapter.java
> +                                    "options", groupedSuggestions.get(propertyName.name)))));
done

2021-11-09 10:22 UTC, upendrakumbham commented on src/main/java/uk/ac/ebi/atlas/search/suggester/SolrSuggestionReactSelectAdapter.java
> +    private static JsonArray getBioEntitySuggestionsForReact(Map<String, List<ImmutableMap<String, String>>> groupedSuggestions) {
done

2021-11-09 10:37 UTC, upendrakumbham commented on src/main/java/uk/ac/ebi/atlas/solr/cloud/collections/BioentitiesCollectionProxy.java
> +    public static final ImmutableList<BioentityPropertyName> BIOENTITY_PROPERTY_NAMES =
`ID_PROPERTY_NAMES` constant we are using many places in the code base as a static import. By following this constant name, we mentioned  `idPropertyNames` as a variable name in many places. So, Analytics and Bioentity suggestions code base is also in one place. I think that it will improve readability if I change the constant name as well as I'm changing variable names as part of review comments.

2021-11-16 15:17 UTC, alfonsomunozpomer approved these changes
All good here.

2021-11-16 23:28 UTC, merged

2021-11-29 14:19 UTC, pcm32 commented on src/main/java/uk/ac/ebi/atlas/solr/cloud/collections/BioentitiesCollectionProxy.java
> -    public static final BioentitiesSchemaField BIOENTITY_IDENTIFIER_DV =
@upendrakumbham there is a class in Bulk that uses this `BIOENTITY_IDENTIFIER_DV` (SpeciesBioentityFInder). What would be the replacement for BIOENTITY_IDENTIFIER_DV now in bulk? It is not clear to me from these changes that an alternative was introduced upon this removal. Thanks!

2021-11-29 14:22 UTC, pcm32 commented on src/main/java/uk/ac/ebi/atlas/solr/cloud/collections/BioentitiesCollectionProxy.java
> -    public static final BioentitiesSchemaField BIOENTITY_IDENTIFIER_DV =
Or is it just a matter of re-adding?
```
public static final BioentitiesSchemaField BIOENTITY_IDENTIFIER_DV =
            new BioentitiesSchemaField("bioentity_identifier_dv");
```
?

2021-11-29 14:44 UTC, upendrakumbham commented
Hi @pcm32, Above new class added by @alfonsomunozpomer as part of CLI - https://github.com/ebi-gene-expression-group/atlas-web-bulk/pull/88. @alfonsomunozpomer would have an idea on this equivalent filed on the bulk side.

2021-11-30 14:42 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/solr/cloud/collections/BioentitiesCollectionProxy.java
> -    public static final BioentitiesSchemaField BIOENTITY_IDENTIFIER_DV =
Yes, this shouldn’t have been removed.