Feature/179434417 add more files for pride rebased core
ebi-gene-expression-group/atlas-web-core pull request #78
Opened 2021-11-30 11:35 UTC by lingyun1010

We add two more files for proteomic experiment    
1. the unprocessed raw output file (`accession-proteinGroups.txt`)
2. the parameter file (`accession.mqpar.xml`)

2021-12-01 14:31 UTC, upendrakumbham commented on src/main/java/uk/ac/ebi/atlas/experimentpage/ExperimentDownloadSupplier.java
> +import uk.ac.ebi.atlas.profiles.stream.*;
Remove *  package import. Better go with specific imports.

2021-12-01 14:32 UTC, upendrakumbham commented on src/main/java/uk/ac/ebi/atlas/experimentpage/StaticFilesDownload.java
> +
I think it is extra space.

2021-12-01 14:32 UTC, upendrakumbham commented on src/main/java/uk/ac/ebi/atlas/experimentpage/StaticFilesDownload.java
> +
Remove it.

2021-12-01 14:33 UTC, upendrakumbham commented on src/main/java/uk/ac/ebi/atlas/experimentpage/StaticFilesDownload.java
> +        }
Use `var ` in applicable places.

2021-12-01 14:35 UTC, upendrakumbham commented on src/main/java/uk/ac/ebi/atlas/experimentpage/StaticFilesDownload.java
> +        public String downloadRawMaxquant(@PathVariable String experimentAccession) {
Use` var` here as well.

2021-12-02 11:05 UTC, alfonsomunozpomer requested changes
Some typos left to fix.

2021-12-02 11:05 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/experimentpage/StaticFilesDownload.java
> +        Path rawMaxquant = dataFileHub.getExperimentMageTabDirLocation()
`rawMaxQuant`

2021-12-02 11:05 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/experimentpage/StaticFilesDownload.java
> +    private static final String RAW_MAXQUANT_URL = URL_BASE + "-proteinGroups.txt";
`RAW_MAX_QUANT_URL`

2021-12-02 11:05 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/experimentpage/StaticFilesDownload.java
> +        public String downloadRawMaxquant(@PathVariable String experimentAccession) {
`downloadRawMaxQuant`

2021-12-02 11:05 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/resource/DataFileHub.java
> +    protected static final String PROTEOMICS_RAW_MAXQAUNT_PATH_TEMPLATE = "{0}/{0}-proteinGroups.txt";
`PROTEOMICS_RAW_MAX_QUANT_PATH_TEMPLATE`

2021-12-03 11:51 UTC, upendrakumbham approved these changes
All Good! Please merge.

2021-12-03 11:58 UTC, merged