Feature/180081614 add new baseline proteomics experiment type 'PROTEOMICS_BASELINE_DIA_SWATH'
ebi-gene-expression-group/atlas-web-core pull request #81
Opened 2021-12-03 10:02 UTC by upendrakumbham

This PR target is to add a new experiment type: PROTEOMICS_BASELINE_DIA_SWATH in the bulk application and displays its corresponding units RA-relative abundant instead of PPB.

Bulk associative PR: [https://github.com/ebi-gene-expression-group/atlas-web-bulk/pull/96](https://github.com/ebi-gene-expression-group/atlas-web-bulk/pull/96)

2021-12-03 16:58 UTC, alfonsomunozpomer requested changes
Please have a look at my comments.

2021-12-03 16:58 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentType.java
> +    PROTEOMICS_BASELINE_DIA_SWATH("proteomics_baseline_dia_swath", "Proteomics baseline dia-swath");
Check with PRIDE how this should be properly spelled. From a few minutes looking around I think it’s DIA/SWATH but better ask the experts.

2021-12-03 16:58 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/model/ExpressionUnit.java
> +             */
Delete comments if they provide no useful information.

2021-12-03 16:58 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/web/ProteomicsBaselineRequestPreferences.java
> +    }
I think this is a somewhat convoluted solution. It’s not very expressive and can be confusing to other people reading the code.

For instance, what is a “new type”? If we add a new type of experiment, what will new refer to? If there are three proteomics baseline experiment types, will this new type cut it, or will we need an old, not-so-new and new type? What does `setUnit` do? If it’s a setter, shouldn’t it allow an argument to set the unit to something?

I suggest you look at `RnaSeqBaselineRequestPreferences` where we approached this problem in a different, more expressive way. Apply the pattern in that class so that we have a consistent solution.

2021-12-06 09:00 UTC, lingyun1010 commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentType.java
> +    SINGLE_CELL_RNASEQ_MRNA_BASELINE("scrnaseq_mrna_baseline", "Single-cell RNA-Seq mRNA baseline"),
Here is a merge issue. This experiment type is already defined.

2021-12-06 09:43 UTC, upendrakumbham commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentType.java
> +    SINGLE_CELL_RNASEQ_MRNA_BASELINE("scrnaseq_mrna_baseline", "Single-cell RNA-Seq mRNA baseline"),
Above one, I fixed it @lingyun1010 in my local. Still, I have conflicts in the bulk after the develop branch merge, I'm working on them. Once I'm done testing I will push altogether.

2021-12-09 10:01 UTC, upendrakumbham commented on src/main/java/uk/ac/ebi/atlas/model/ExpressionUnit.java
> +             */
Done

2021-12-09 10:05 UTC, upendrakumbham commented on src/main/java/uk/ac/ebi/atlas/web/ProteomicsBaselineRequestPreferences.java
> +    }
I'm not happy when I followed that boolean approach to display corresponding data units. Thanks for the reference codebase. I improved approach as per  `RnaSeqBaselineRequestPreferences` class.

2021-12-09 10:07 UTC, upendrakumbham commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentType.java
> +    SINGLE_CELL_RNASEQ_MRNA_BASELINE("scrnaseq_mrna_baseline", "Single-cell RNA-Seq mRNA baseline"),
Please review the code @lingyun1010 and test functionality as per the description. Let me know if you face any issues while running PR.

2021-12-09 10:12 UTC, upendrakumbham commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentType.java
> +    PROTEOMICS_BASELINE_DIA_SWATH("proteomics_baseline_dia_swath", "Proteomics baseline dia-swath");
Needs to get final confirmation on this from @Curators.

2021-12-15 10:11 UTC, alfonsomunozpomer approved these changes
Fix the two typos I highlighted in the review and merge, all good.

2021-12-15 10:11 UTC, alfonsomunozpomer commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentType.java
> +    PROTEOMICS_BASELINE_DIA("proteomics_baseline_dia", "Proteomics baseline dia");
Remember that DIA is an acronym (“data independent acquisition”) and it should be upper-cased.

2021-12-15 10:11 UTC, alfonsomunozpomer commented on src/test/java/uk/ac/ebi/atlas/experiments/ExperimentJsonSerializerTest.java
> +    void canSerializeProteomicsBaselineDiaSwathExperiments() {
This should now be renamed to `canSerializeProteomicsBaselineDiaExperiments()`.

2021-12-16 11:36 UTC, upendrakumbham commented on src/main/java/uk/ac/ebi/atlas/model/experiment/ExperimentType.java
> +    PROTEOMICS_BASELINE_DIA("proteomics_baseline_dia", "Proteomics baseline dia");
Fixed it.

2021-12-16 16:18 UTC, merged