Removes unwanted leading and trailing edges in the Heatmap column labels.
ebi-gene-expression-group/atlas-web-core pull request #85
Opened 2022-01-10 11:12 UTC by upendrakumbham

This PR removes unwanted leading and trailing edges in the Heatmap column labels.

2022-01-10 12:00 UTC, alfonsomunozpomer requested changes
Please add tests.

2022-01-11 13:00 UTC, upendrakumbham commented
> Please add tests.

Hi @alfonsomunozpomer, Added a test scenario to test the empty factor type values.

2022-01-12 14:03 UTC, alfonsomunozpomer requested changes
Please, have a look at the comments I left above for some improvements.

2022-01-12 14:03 UTC, alfonsomunozpomer commented on src/test/java/uk/ac/ebi/atlas/experimentpage/context/BaselineRequestContextTest.java
> +        List<AssayGroup> assayGroups = ImmutableList.of(ag1, ag2, ag3);
The class `RandomDataTestUtils` provides methods such as:
- `generateRandomRnaSeqRunId()`
- `generateRandomAssayGroupId()`
- `generateRandomAssayGroup()` 
- `generateRandomAssayGroups(int count)`

Think if you could randomise your test subjects.

2022-01-14 00:21 UTC, upendrakumbham commented on src/main/java/uk/ac/ebi/atlas/experimentpage/context/BaselineRequestContext.java
> +                            .filter(StringUtils::isNotBlank)
done

2022-01-14 00:22 UTC, upendrakumbham commented on src/test/java/uk/ac/ebi/atlas/experimentpage/context/BaselineRequestContextTest.java
> +        String defaultQueryFactorType = "defaultQueryFactorType";
Sorry, fixed it for all the tests.

2022-01-14 00:22 UTC, upendrakumbham commented on src/test/java/uk/ac/ebi/atlas/experimentpage/context/BaselineRequestContextTest.java
> +        List<AssayGroup> assayGroups = ImmutableList.of(ag1, ag2, ag3);
Randomised all tests how much I can.

2022-01-18 11:00 UTC, alfonsomunozpomer approved these changes
Looks good. Thanks for cleaning the test code.

2022-01-18 11:26 UTC, merged